---

# Primers - uncomment the correct set

# Illumina V3-V4 protocol primers
fwd_primer: "CCTACGGGNGGCWGCAG"
rev_primer: "GACTACHVGGGTATCTAATCC"
fwd_primer_rc: "CTGCWGCCNCCCGTAGG" 
rev_primer_rc: "GGATTAGATACCCBDGTAGTC"

# V4 primers: 515F-806R
# fwd_primer: "GTGCCAGCMGCCGCGGTAA"
# rev_primer: "GGACTACHVGGGTWTCTAAT"
# fwd_primer_rc: "TTACCGCGGCMGCTGGCAC"
# rev_primer_rc: "ATTAGAWACCCVHGTAGTCC"


run_name: "test" 
read_directory: "data"
    
# Pre-trim at this qual cutoff with cutadapt
q_trim: 20

# max value for expected error for read filtering. Increase to reduce stringency.
max_expected_error: 1.0 

# Truncate all reads at this length (fwd, rev)
truncLen: 0
trimLeft: 0

# number of threads 
num_threads: 2 

samples: []

